### PR TITLE
bug fix and some enhancement

### PR DESCRIPTION
**Pull request by lq**
Fixed the "empty terminal" bug. Also made the parser distinguish unary/binary +/- and recognize `]]` (named `RBB`, which closes `LBB`).

### CODE REVIEW

**Comment by lq** [comment]
the fix was faulty

**Comment by halpo** [comment]
Is this supposed to fix the if parse problem in issue #2 or another problem?  If so please show the problem that it is solving so that I can test for it.

**Comment by lq** [comment]
Yes, it is to fix issue #2. Since it is interlaced with the new token `RBB` in my branch, I opened this new issue, but I failed to find the method for making a reference. A minimal testcase was included in the description of issue #2. For the minor enhancements (unary +/-, `]]`), please just look at the results for parsing `-x[[1]]`. I made these changes so that when sweaving documents I can a) adjust spaces around binary +/- without affecting unary ones; b) easily replace `]]` with a single character (`⟧`, U+27E7). I think it is also preferable to be able to detect these tokens for general purpose, and we already had `UPLUS`, `UMINUS` and `LBB` in `gram.y` from the beginning.

**Comment by halpo** [comment]
I had to refix the stderr bug in this pull before i could merge it.  It is there now.

**Pull request closed without merging**
